[book]
#title = "Example book"
#author = "John Doe"
description = "The example book covers examples."
language = "zh-Hans"

[build]
build-dir = "docs"
create-missing = false
mathjax = true

[preprocessor.index]

[preprocessor.links]

[output.html]
additional-css = ["custom.css"]
mathjax-support = true
highlight-theme = "github"
site-url = "/study-note/"
mathjax = true




[output.html.search]
limit-results = 15

[output.html.playground.markdown]
image_directory = "images"

[output.html.math]
enable = true

[output.html.playground]
editable = true

[book.preprocessors]
search = { name = "mdbook-search" }
