[book]
#title = "Example book"
#author = "John Doe"
description = "The example book covers examples."
language = "zh-Hans"

[build]
build-dir = "docs"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[output.html]
highlight-theme = "github"
site-url = "/study-note/"
additional-css = ["assets/css/custom.css"]


[output.html.search]
limit-results = 15

[output.html.playground.markdown]
image_directory = "images"

enable = true

[output.html.playground]
editable = true

[book.preprocessors]
search = { name = "mdbook-search" }
